class Event:
    #base class for events in the system
    pass

class MarketEvent(Event):
    #represents the arrival of new data
    def __init__(self):
        self.type = "MARKET"

class SignalEvent(Event):
    #represents a trading signal generated by a strategy
    def __init__(self, strategy_id, symbol, datetime, signal_type, strength):
        self.type = "SIGNAL"
        self.strategy_id = strategy_id
        self.symbol = symbol
        self.datetime = datetime
        self.signal_type = signal_type
        self.strength = strength

class OrderEvent(Event):
    #represents an instruction to buy or sell an asset
    def __init__(self, symbol, order_type, quantity, direction):
        self.type = "ORDER"
        self.symbol = symbol
        self.order_type = order_type
        self.quantity = quantity
        self.direction = direction
    
    def print_order(self):
        print(
            f"Order: Symbol={self.symbol}, "
            f"Type={self.order_type}, "
            f"Quantity={self.quantity}, "
            f"Direction={self.direction}"
        )

class FillEvent(Event):
    #represents an executed order
    def __init__(
            self,
            timeindex,
            symbol,
            exchange,
            quantity,
            direction,
            fill_cost,
            commission=None,
    ):
        self.type = "FILL"
        self.timeindex = timeindex
        self.symbol = symbol
        self.exchange = exchange
        self.quantity = quantity
        self.direction = direction
        self.fill_cost = fill_cost

        if commission is None:
            self.commission = self.calculate_commission()
        else:
            self.commission = commission

    def calculate_commission(self):
        #calculates a simple simulated broker commission
        if self.quantity <= 500:
            return max(1.30, 0.013 * self.quantity)
        
        return max(1.30, 0.08 * self.quantity)
    