class Event:
    #base class for events in the system
    pass

class MarketEvent(Event):
    #represents the arrival of new data
    def __init__(self):
        self.type = "MARKET"

class SignalEvent(Event):
    #represents a trading signal generated by a strategy
    def __init__(self, strategy_id, symbol, datetime, signal_type, strength):
        self.type = "SIGNAL"
        self.strategy_id = strategy_id
        self.symbol = symbol
        self.datetime = datetime
        self.signal_type = signal_type
        self.strength = strength

class OrderEvent(Event):
    #represents an instruction to buy or sell an asset
    def __init__(self, symbol, order_type, quantity, direction):
        self.type = "ORDER"
        self.symbol = symbol
        self.order_type = order_type
        self.quantity = quantity
        self.direction = direction
    
    def print_order(self):
        print(
            f"Order: Symbol={self.symbol}, "
            f"Type={self.order_type}, "
            f"Quantity={self.quantity}, "
            f"Direction={self.direction}"
        )

order = OrderEvent(
    symbol="AAPL",
    order_type="MKT",
    quantity=100,
    direction="BUY",
)

order.print_order()